### ISSUE TITLE
[WIP] Compiling NRPE from source

### ISSUE THREAD

**Issue by bernardoVale** [jloh/nagios-nrpe-server#15]
Hello, I'm trying to add support for AIX, HP-UX, OpenSUSE and Suse Enterprise.

Some of those OS doesn't have a package for NRPE. When I need to install NRPE on those, I've generally compile nrpe from source.

I've really liked your role and I was wondering if we could use this approach to support those Operating Systems. I'm already working on this at my fork, if you find a better way please let me know.

**Comment by Mooash** [comment]
Hey! This sounds great. Compiling from source is often a tricky one though since people might have private repos that contain a custom build. It also means possibly changing how CI tests are done to get test coverage (this could be optional though of course and not something I expect you to work out).

So go for it but make it optional at this point and then we'll go from there!

**Comment by bernardoVale** [comment]
From some OS, like, AIX 7.1, HP-UX, SLES 11 SP1, this is the only way to get nrpe.

I'm expecting to compile only on those OS. I think it's an overkill to compile NRPE where there is a package for it's installation.

For a better test coverage on CI we could use Docker. If you like to check it out I'm using this approach on one of my roles [here](https://github.com/bernardoVale/ansible-role-db2/blob/master/.travis.yml) 

Thank you!

**Comment by jloh** [comment]
Hey @bernardoVale, just checking whether you ended up getting around to this in the end?

**Comment by bernardoVale** [comment]
Hi @jloh , I wasn't able to go further on this issue. I'm not working with NRPE anymore. Close this issue if you want to.

**Comment by jloh** [comment]
No worries, thanks!
